# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["crate::models::{status::Status, visibility::Visibility}", "diesel::sql_types::*"]
